modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/Mrbysco/WeirdCommands/issues"
license="MIT"

[[mods]]
modId="weirdcommands"
version="${file.jarVersion}"
displayName="Weird Commands"
displayURL="https://www.curseforge.com/minecraft/mc-mods/weird-commands"
authors="Mrbysco"
description='''
Adding commands to things that don't need one
'''
[[dependencies.weirdcommands]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"