modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/WeirdCommands/issues"
license="MIT"

[[mods]]
modId="weirdcommands"
version="${file.jarVersion}"
displayName="Weird Commands"
displayURL="https://www.curseforge.com/minecraft/mc-mods/weird-commands"
authors="Mrbysco"
description='''
Adding commands to things that don't need one
'''
[[dependencies.weirdcommands]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.weirdcommands]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.70-beta,)"
ordering="NONE"
side="BOTH"